export interface QBittorrentPreferences {
	locale: string
	confirm_torrent_deletion: boolean
	status_bar_external_ip: boolean
	performance_warning: boolean
	file_log_enabled: boolean
	file_log_path: string
	file_log_max_size: number
	file_log_age: number
	file_log_age_type: number
	file_log_backup_enabled: boolean
	file_log_delete_old: boolean

	torrent_content_layout: 'Original' | 'Subfolder' | 'NoSubfolder'
	add_to_top_of_queue: boolean
	add_stopped_enabled: boolean
	torrent_stop_condition: 'None' | 'MetadataReceived' | 'FilesChecked'
	merge_trackers: boolean
	auto_delete_mode: number
	preallocate_all: boolean
	incomplete_files_ext: boolean
	use_unwanted_folder: boolean
	save_path: string
	temp_path: string
	temp_path_enabled: boolean
	export_dir: string
	export_dir_fin: string
	auto_tmm_enabled: boolean
	torrent_changed_tmm_enabled: boolean
	save_path_changed_tmm_enabled: boolean
	category_changed_tmm_enabled: boolean
	use_subcategories: boolean
	use_category_paths_in_manual_mode: boolean
	scan_dirs: Record<string, number | string>
	excluded_file_names_enabled: boolean
	excluded_file_names: string
	mail_notification_enabled: boolean
	mail_notification_sender: string
	mail_notification_email: string
	mail_notification_smtp: string
	mail_notification_ssl_enabled: boolean
	mail_notification_auth_enabled: boolean
	mail_notification_username: string
	mail_notification_password: string
	autorun_on_torrent_added_enabled: boolean
	autorun_on_torrent_added_program: string
	autorun_enabled: boolean
	autorun_program: string

	listen_port: number
	upnp: boolean
	random_port: boolean
	max_connec: number
	max_connec_per_torrent: number
	max_uploads: number
	max_uploads_per_torrent: number
	i2p_enabled: boolean
	i2p_address: string
	i2p_port: number
	i2p_mixed_mode: boolean
	i2p_inbound_quantity: number
	i2p_outbound_quantity: number
	i2p_inbound_length: number
	i2p_outbound_length: number
	proxy_type: number
	proxy_ip: string
	proxy_port: number
	proxy_auth_enabled: boolean
	proxy_username: string
	proxy_password: string
	proxy_bittorrent: boolean
	proxy_peer_connections: boolean
	proxy_hostname_lookup: boolean
	proxy_rss: boolean
	proxy_misc: boolean
	ip_filter_enabled: boolean
	ip_filter_path: string
	ip_filter_trackers: boolean
	banned_IPs: string

	dl_limit: number
	up_limit: number
	alt_dl_limit: number
	alt_up_limit: number
	scheduler_enabled: boolean
	schedule_from_hour: number
	schedule_from_min: number
	schedule_to_hour: number
	schedule_to_min: number
	scheduler_days: number
	limit_utp_rate: boolean
	limit_tcp_overhead: boolean
	limit_lan_peers: boolean
	bittorrent_protocol: number

	dht: boolean
	pex: boolean
	lsd: boolean
	encryption: number
	anonymous_mode: boolean
	max_active_checking_torrents: number
	queueing_enabled: boolean
	max_active_downloads: number
	max_active_uploads: number
	max_active_torrents: number
	dont_count_slow_torrents: boolean
	slow_torrent_dl_rate_threshold: number
	slow_torrent_ul_rate_threshold: number
	slow_torrent_inactive_timer: number
	max_ratio_enabled: boolean
	max_ratio: number
	max_ratio_act: number
	max_seeding_time_enabled: boolean
	max_seeding_time: number
	max_inactive_seeding_time_enabled: boolean
	max_inactive_seeding_time: number

	rss_refresh_interval: number
	rss_fetch_delay: number
	rss_max_articles_per_feed: number
	rss_processing_enabled: boolean
	rss_auto_downloading_enabled: boolean
	rss_download_repack_proper_episodes: boolean
	rss_smart_episode_filters: string

	web_ui_port: number
	web_ui_address: string
	web_ui_domain_list: string
	web_ui_upnp: boolean
	use_https: boolean
	web_ui_https_cert_path: string
	web_ui_https_key_path: string
	web_ui_username: string
	bypass_local_auth: boolean
	bypass_auth_subnet_whitelist_enabled: boolean
	bypass_auth_subnet_whitelist: string
	web_ui_max_auth_fail_count: number
	web_ui_ban_duration: number
	web_ui_session_timeout: number
	web_ui_clickjacking_protection_enabled: boolean
	web_ui_csrf_protection_enabled: boolean
	web_ui_secure_cookie_enabled: boolean
	web_ui_host_header_validation_enabled: boolean
	web_ui_use_custom_http_headers_enabled: boolean
	web_ui_custom_http_headers: string
	web_ui_reverse_proxy_enabled: boolean
	web_ui_reverse_proxies_list: string
	alternative_webui_enabled: boolean
	alternative_webui_path: string
	dyndns_enabled: boolean
	dyndns_service: number
	dyndns_domain: string
	dyndns_username: string
	dyndns_password: string

	resume_data_storage_type: string
	torrent_content_remove_option: string
	memory_working_set_limit: number
	current_network_interface: string
	current_interface_name: string
	current_interface_address: string
	save_resume_data_interval: number
	save_statistics_interval: number
	torrent_file_size_limit: number
	confirm_torrent_recheck: boolean
	recheck_completed_torrents: boolean
	app_instance_name: string
	refresh_interval: number
	resolve_peer_countries: boolean
	reannounce_when_address_changed: boolean
	enable_embedded_tracker: boolean
	embedded_tracker_port: number
	embedded_tracker_port_forwarding: boolean
	ignore_ssl_errors: boolean
	python_executable_path: string

	bdecode_depth_limit: number
	bdecode_token_limit: number
	async_io_threads: number
	hashing_threads: number
	file_pool_size: number
	checking_memory_use: number
	disk_cache: number
	disk_cache_ttl: number
	disk_queue_size: number
	disk_io_type: number
	disk_io_read_mode: number
	disk_io_write_mode: number
	enable_coalesce_read_write: boolean
	enable_piece_extent_affinity: boolean
	enable_upload_suggestions: boolean
	send_buffer_watermark: number
	send_buffer_low_watermark: number
	send_buffer_watermark_factor: number
	connection_speed: number
	socket_send_buffer_size: number
	socket_receive_buffer_size: number
	socket_backlog_size: number
	outgoing_ports_min: number
	outgoing_ports_max: number
	upnp_lease_duration: number
	peer_tos: number
	utp_tcp_mixed_mode: number
	idn_support_enabled: boolean
	enable_multi_connections_from_same_ip: boolean
	validate_https_tracker_certificate: boolean
	ssrf_mitigation: boolean
	block_peers_on_privileged_ports: boolean
	upload_slots_behavior: number
	upload_choking_algorithm: number
	announce_to_all_trackers: boolean
	announce_to_all_tiers: boolean
	announce_ip: string
	announce_port: number
	max_concurrent_http_announces: number
	stop_tracker_timeout: number
	peer_turnover: number
	peer_turnover_cutoff: number
	peer_turnover_interval: number
	request_queue_size: number
	dht_bootstrap_nodes: string
	add_trackers_enabled: boolean
	add_trackers: string
	add_trackers_from_url_enabled: boolean
	add_trackers_url: string
	add_trackers_url_list: string
}
